using System.Globalization;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Core.AudioDirector.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class AddAudioTrackWindow : DefaultWindow
{
    private readonly int _groupId;
    private bool _loop;

    public event Action<int, string, string, float, bool>? OnAddTrackRequested;

    public AddAudioTrackWindow(
        int groupId,
        string groupName)
    {
        RobustXamlLoader.Load(this);

        _groupId = groupId;

        GroupLabel.Text =
            $"Group: {groupName}";

        LoopOption.AddItem("No", 0);
        LoopOption.AddItem("Yes", 1);

        LoopOption.OnItemSelected += args =>
        {
            LoopOption.SelectId(args.Id);
            _loop = args.Id == 1;
            ClearError();
        };

        LoopOption.SelectId(0);

        TrackNameEdit.OnTextChanged += _ =>
        {
            ClearError();
            UpdateAddButton();
        };

        TrackPathEdit.OnTextChanged += _ =>
        {
            ClearError();
            UpdateAddButton();
        };

        VolumeEdit.OnTextChanged += _ =>
        {
            ClearError();
            UpdateAddButton();
        };

        CancelButton.OnPressed += _ =>
            Close();

        AddButton.OnPressed += _ =>
            TryAdd();

        UpdateAddButton();
    }

    private void UpdateAddButton()
    {
        AddButton.Disabled =
            !HasValidInput();
    }

    private bool HasValidInput()
    {
        if (string.IsNullOrWhiteSpace(TrackNameEdit.Text))
            return false;

        if (string.IsNullOrWhiteSpace(TrackPathEdit.Text))
            return false;

        if (!TryParseVolume(out _))
            return false;

        return true;
    }

    private void TryAdd()
    {
        var name = TrackNameEdit.Text.Trim();
        var path = TrackPathEdit.Text.Trim();

        if (string.IsNullOrWhiteSpace(name))
            return;

        if (string.IsNullOrWhiteSpace(path))
            return;

        if (!TryParseVolume(out var volume))
            return;

        OnAddTrackRequested?.Invoke(
            _groupId,
            name,
            path,
            volume,
            _loop);
    }

    private bool TryParseVolume(out float volume)
    {
        if (!float.TryParse(
                VolumeEdit.Text,
                NumberStyles.Float,
                CultureInfo.InvariantCulture,
                out volume))
        {
            return false;
        }

        return !float.IsNaN(volume)
               && !float.IsInfinity(volume)
               && volume >= 0f
               && volume <= 2f;
    }

    public void ShowError(string error)
    {
        ErrorLabel.Text = error;
        ErrorLabel.Visible = true;
    }

    private void ClearError()
    {
        ErrorLabel.Text = string.Empty;
        ErrorLabel.Visible = false;
    }
}
