using Content.Client._Core.AudioDirector.UI.Controls;
using Content.Shared._Core.AudioDirector.Eui;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Core.AudioDirector.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class AudioDirectorWindow : DefaultWindow
{
    private readonly Dictionary<int, bool> _groupExpandedStates = new();
    private readonly Dictionary<int, AudioGroupEuiData> _groupsById = new();

    private bool _removeMode;

    public event Action? OnAddGroupPressed;
    public event Action<int>? OnDeleteGroupPressed;
    public event Action<int>? OnEditGroupPressed;
    public event Action<int>? OnAddTrackPressed;
    public event Action<int, int>? OnDeleteTrackPressed;
    public event Action<int, int, float, bool>? OnUpdateTrackPressed;
    public event Action<int, int, bool>? OnSetTrackPausedPressed;
    public event Action<int, int, float>? OnSetTrackTimePressed;
    public event Action<int, int, float, bool>? OnFadeTrackPressed;

    public AudioDirectorWindow()
    {
        RobustXamlLoader.Load(this);

        AddGroupButton.OnPressed += _ =>
            OnAddGroupPressed?.Invoke();

        RemoveModeButton.OnPressed += _ =>
            ToggleRemoveMode();
    }

    public void SetGroups(AudioGroupEuiData[] groups)
    {
        _groupsById.Clear();

        foreach (var group in groups)
        {
            _groupsById[group.Id] = group;
        }

        GroupsContainer.RemoveAllChildren();

        if (groups.Length == 0)
        {
            GroupsContainer.AddChild(new Label
            {
                Text = "No audio groups created.",
                HorizontalAlignment = HAlignment.Center
            });

            RemoveModeButton.Disabled = true;
            return;
        }

        RemoveModeButton.Disabled = false;

        foreach (var group in groups)
        {
            var expanded = !_groupExpandedStates.TryGetValue(
                               group.Id,
                               out var savedExpanded)
                           || savedExpanded;

            var card = new AudioGroupCard(
                group,
                expanded);

            card.SetRemoveMode(_removeMode);

            card.OnExpandedChanged +=
                OnGroupExpandedChanged;

            card.OnDeletePressed += groupId =>
                OnDeleteGroupPressed?.Invoke(groupId);

            card.OnEditPressed += groupId =>
                OnEditGroupPressed?.Invoke(groupId);

            card.OnAddTrackPressed += groupId =>
                OnAddTrackPressed?.Invoke(groupId);

            card.OnDeleteTrackPressed += (groupId, trackId) =>
                OnDeleteTrackPressed?.Invoke(groupId, trackId);

            card.OnUpdateTrackPressed += (groupId, trackId, volume, loop) =>
                OnUpdateTrackPressed?.Invoke(groupId, trackId, volume, loop);

            card.OnSetTrackPausedPressed += (groupId, trackId, paused) =>
                OnSetTrackPausedPressed?.Invoke(groupId, trackId, paused);

            card.OnSetTrackTimePressed += (groupId, trackId, time) =>
                OnSetTrackTimePressed?.Invoke(groupId, trackId, time);

            card.OnFadeTrackPressed += (groupId, trackId, duration, fadeIn) =>
                OnFadeTrackPressed?.Invoke(groupId, trackId, duration, fadeIn);

            GroupsContainer.AddChild(card);
        }
    }

    private void ToggleRemoveMode()
    {
        _removeMode = !_removeMode;
        UpdateRemoveMode();
    }

    private void OnGroupExpandedChanged(
        int groupId,
        bool expanded)
    {
        _groupExpandedStates[groupId] = expanded;
    }

    private void UpdateRemoveMode()
    {
        foreach (var child in GroupsContainer.Children)
        {
            if (child is AudioGroupCard card)
                card.SetRemoveMode(_removeMode);
        }
    }
}
