using System.Linq;
using Content.Shared._Core.AudioDirector;
using Content.Shared._Core.AudioDirector.Eui;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Network;

namespace Content.Client._Core.AudioDirector.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class CreateAudioGroupWindow : DefaultWindow
{
    private readonly HashSet<NetUserId> _selectedPlayers = new();
    private readonly Dictionary<NetUserId, Button> _playerButtons = new();
    private readonly Dictionary<NetUserId, string> _playerNames = new();

    private AudioGroupTargetType _selectedType = AudioGroupTargetType.Grid;

    public event Action<string, int>? OnCreateMapGroupRequested;
    public event Action<string, string>? OnCreateGridGroupRequested;
    public event Action<string, NetUserId[]>? OnCreatePlayersGroupRequested;

    public CreateAudioGroupWindow(
        AudioDirectorPlayerEuiData[] players)
    {
        RobustXamlLoader.Load(this);

        GroupNameEdit.OnTextChanged += _ =>
        {
            ClearError();
            UpdateCreateButton();
        };

        GridUidEdit.OnTextChanged += _ =>
        {
            ClearError();
            UpdateCreateButton();
        };

        MapIdEdit.OnTextChanged += _ =>
        {
            ClearError();
            UpdateCreateButton();
        };

        TargetTypeOption.AddItem(
            "Grid",
            (int) AudioGroupTargetType.Grid);

        TargetTypeOption.AddItem(
            "Map",
            (int) AudioGroupTargetType.Map);

        TargetTypeOption.AddItem(
            "Players",
            (int) AudioGroupTargetType.Players);

        TargetTypeOption.OnItemSelected += args =>
        {
            TargetTypeOption.SelectId(args.Id);
            SelectType((AudioGroupTargetType) args.Id);
        };

        TargetTypeOption.SelectId(
            (int) AudioGroupTargetType.Grid);

        SelectType(AudioGroupTargetType.Grid);
        SetPlayers(players);

        CreateButton.OnPressed += _ =>
            TryCreateGroup();
    }

    public void SetPlayers(
        AudioDirectorPlayerEuiData[] players)
    {
        var onlinePlayers = players
            .Select(player => player.UserId)
            .ToHashSet();

        _selectedPlayers.IntersectWith(onlinePlayers);
        _playerButtons.Clear();
        _playerNames.Clear();
        PlayersList.RemoveAllChildren();

        if (players.Length == 0)
        {
            PlayersList.AddChild(new Label
            {
                Text = "No players online.",
                HorizontalAlignment = HAlignment.Center
            });

            UpdateCreateButton();
            return;
        }

        foreach (var player in players.OrderBy(player => player.Name))
        {
            var playerButton = new Button
            {
                HorizontalExpand = true
            };

            playerButton.OnPressed += _ =>
                TogglePlayer(player.UserId);

            _playerButtons[player.UserId] = playerButton;
            _playerNames[player.UserId] = player.Name;

            PlayersList.AddChild(playerButton);

            UpdatePlayerButton(
                player.UserId,
                player.Name);
        }

        UpdateCreateButton();
    }

    private void SelectType(AudioGroupTargetType type)
    {
        _selectedType = type;

        GridTargetEditor.Visible =
            type == AudioGroupTargetType.Grid;

        MapTargetEditor.Visible =
            type == AudioGroupTargetType.Map;

        PlayersTargetEditor.Visible =
            type == AudioGroupTargetType.Players;

        UpdateCreateButton();
        ClearError();
    }

    private void TogglePlayer(NetUserId userId)
    {
        if (!_selectedPlayers.Add(userId))
            _selectedPlayers.Remove(userId);

        if (_playerNames.TryGetValue(
                userId,
                out var name))
        {
            UpdatePlayerButton(
                userId,
                name);
        }

        ClearError();
        UpdateCreateButton();
    }

    private void UpdatePlayerButton(
        NetUserId userId,
        string name)
    {
        if (!_playerButtons.TryGetValue(
                userId,
                out var button))
        {
            return;
        }

        button.Text = _selectedPlayers.Contains(userId)
            ? $"[x] {name}"
            : $"[ ] {name}";
    }

    private void TryCreateGroup()
    {
        var name = GroupNameEdit.Text.Trim();

        if (string.IsNullOrWhiteSpace(name))
            return;

        switch (_selectedType)
        {
            case AudioGroupTargetType.Grid:
            {
                var gridNetEntityId =
                    GridUidEdit.Text.Trim();

                if (!NetEntity.TryParse(
                        gridNetEntityId,
                        out _))
                {
                    return;
                }

                OnCreateGridGroupRequested?.Invoke(
                    name,
                    gridNetEntityId);

                break;
            }

            case AudioGroupTargetType.Map:
            {
                if (!int.TryParse(
                        MapIdEdit.Text,
                        out var mapId))
                {
                    return;
                }

                OnCreateMapGroupRequested?.Invoke(
                    name,
                    mapId);

                break;
            }

            case AudioGroupTargetType.Players:
            {
                var players =
                    _selectedPlayers.ToArray();

                if (players.Length == 0)
                    return;

                OnCreatePlayersGroupRequested?.Invoke(
                    name,
                    players);

                break;
            }
        }
    }

    public void ShowError(string error)
    {
        ErrorLabel.Text = error;
        ErrorLabel.Visible = true;
    }

    public void ClearError()
    {
        ErrorLabel.Text = string.Empty;
        ErrorLabel.Visible = false;
    }

    private void UpdateCreateButton()
    {
        var hasName =
            !string.IsNullOrWhiteSpace(GroupNameEdit.Text);

        var hasValidTarget = _selectedType switch
        {
            AudioGroupTargetType.Grid =>
                NetEntity.TryParse(GridUidEdit.Text, out _),

            AudioGroupTargetType.Map =>
                int.TryParse(MapIdEdit.Text, out _),

            AudioGroupTargetType.Players =>
                _selectedPlayers.Count > 0,

            _ => false
        };

        CreateButton.Disabled =
            !hasName || !hasValidTarget;
    }
}
