using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Core.AudioDirector.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class DeleteAudioGroupWindow : DefaultWindow
{
    public int GroupId { get; }

    public event Action<int>? OnDeleteConfirmed;

    public DeleteAudioGroupWindow(
        int groupId,
        string groupName)
    {
        RobustXamlLoader.Load(this);

        GroupId = groupId;

        ConfirmationLabel.Text =
            $"Delete group \"{groupName}\"?";

        CancelButton.OnPressed += _ =>
            Close();

        DeleteButton.OnPressed += _ =>
        {
            OnDeleteConfirmed?.Invoke(GroupId);
            Close();
        };
    }
}
