using System.Linq;
using Content.Shared._Core.AudioDirector;
using Content.Shared._Core.AudioDirector.Eui;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Network;

namespace Content.Client._Core.AudioDirector.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class EditAudioGroupWindow : DefaultWindow
{
    private readonly int _groupId;
    private readonly AudioGroupTargetType _targetType;
    private readonly HashSet<NetUserId> _selectedPlayers = new();
    private readonly Dictionary<NetUserId, Button> _playerButtons = new();
    private readonly Dictionary<NetUserId, string> _playerNames = new();

    public event Action<int, string, string>? OnSaveGridRequested;
    public event Action<int, string, int>? OnSaveMapRequested;
    public event Action<int, string, NetUserId[]>? OnSavePlayersRequested;

    public EditAudioGroupWindow(
        AudioGroupEuiData group,
        AudioDirectorPlayerEuiData[] players)
    {
        RobustXamlLoader.Load(this);

        _groupId = group.Id;
        _targetType = group.TargetType;

        GroupNameEdit.Text = group.Name;
        TargetTypeLabel.Text = group.TargetType.ToString();

        GridTargetEditor.Visible =
            group.TargetType == AudioGroupTargetType.Grid;

        MapTargetEditor.Visible =
            group.TargetType == AudioGroupTargetType.Map;

        PlayersTargetEditor.Visible =
            group.TargetType == AudioGroupTargetType.Players;

        if (group.TargetType == AudioGroupTargetType.Grid)
        {
            GridUidEdit.Text =
                group.GridNetEntityId ?? string.Empty;
        }

        if (group.TargetType == AudioGroupTargetType.Map)
        {
            MapIdEdit.Text =
                group.MapId ?? string.Empty;
        }

        if (group.TargetType == AudioGroupTargetType.Players)
        {
            foreach (var player in group.Players)
            {
                _selectedPlayers.Add(player);
            }

            SetPlayers(players);
        }

        GroupNameEdit.OnTextChanged += _ =>
        {
            ClearError();
            UpdateSaveButton();
        };

        GridUidEdit.OnTextChanged += _ =>
        {
            ClearError();
            UpdateSaveButton();
        };

        MapIdEdit.OnTextChanged += _ =>
        {
            ClearError();
            UpdateSaveButton();
        };

        CancelButton.OnPressed += _ =>
            Close();

        SaveButton.OnPressed += _ =>
            TrySave();

        UpdateSaveButton();
    }

    public void SetPlayers(
        AudioDirectorPlayerEuiData[] players)
    {
        var onlinePlayers = players
            .Select(player => player.UserId)
            .ToHashSet();

        _selectedPlayers.IntersectWith(onlinePlayers);
        _playerButtons.Clear();
        _playerNames.Clear();
        PlayersList.RemoveAllChildren();

        if (players.Length == 0)
        {
            PlayersList.AddChild(new Label
            {
                Text = "No players online.",
                HorizontalAlignment = HAlignment.Center
            });

            UpdateSaveButton();
            return;
        }

        foreach (var player in players.OrderBy(player => player.Name))
        {
            var playerButton = new Button
            {
                HorizontalExpand = true
            };

            playerButton.OnPressed += _ =>
                TogglePlayer(player.UserId);

            _playerButtons[player.UserId] = playerButton;
            _playerNames[player.UserId] = player.Name;

            PlayersList.AddChild(playerButton);

            UpdatePlayerButton(
                player.UserId,
                player.Name);
        }

        UpdateSaveButton();
    }

    private void TogglePlayer(NetUserId userId)
    {
        if (!_selectedPlayers.Add(userId))
            _selectedPlayers.Remove(userId);

        if (_playerNames.TryGetValue(
                userId,
                out var name))
        {
            UpdatePlayerButton(
                userId,
                name);
        }

        ClearError();
        UpdateSaveButton();
    }

    private void UpdatePlayerButton(
        NetUserId userId,
        string name)
    {
        if (!_playerButtons.TryGetValue(
                userId,
                out var button))
        {
            return;
        }

        button.Text = _selectedPlayers.Contains(userId)
            ? $"[x] {name}"
            : $"[ ] {name}";
    }

    private void UpdateSaveButton()
    {
        var hasName =
            !string.IsNullOrWhiteSpace(GroupNameEdit.Text);

        var hasValidTarget = _targetType switch
        {
            AudioGroupTargetType.Grid =>
                NetEntity.TryParse(GridUidEdit.Text, out _),

            AudioGroupTargetType.Map =>
                int.TryParse(MapIdEdit.Text, out _),

            AudioGroupTargetType.Players =>
                _selectedPlayers.Count > 0,

            _ => false
        };

        SaveButton.Disabled =
            !hasName || !hasValidTarget;
    }

    private void TrySave()
    {
        var name = GroupNameEdit.Text.Trim();

        if (string.IsNullOrWhiteSpace(name))
            return;

        switch (_targetType)
        {
            case AudioGroupTargetType.Grid:
            {
                var gridNetEntityId =
                    GridUidEdit.Text.Trim();

                if (!NetEntity.TryParse(
                        gridNetEntityId,
                        out _))
                {
                    return;
                }

                OnSaveGridRequested?.Invoke(
                    _groupId,
                    name,
                    gridNetEntityId);

                break;
            }

            case AudioGroupTargetType.Map:
            {
                if (!int.TryParse(
                        MapIdEdit.Text,
                        out var mapId))
                {
                    return;
                }

                OnSaveMapRequested?.Invoke(
                    _groupId,
                    name,
                    mapId);

                break;
            }

            case AudioGroupTargetType.Players:
            {
                var players =
                    _selectedPlayers.ToArray();

                if (players.Length == 0)
                    return;

                OnSavePlayersRequested?.Invoke(
                    _groupId,
                    name,
                    players);

                break;
            }
        }
    }

    public void ShowError(string error)
    {
        ErrorLabel.Text = error;
        ErrorLabel.Visible = true;
    }

    private void ClearError()
    {
        ErrorLabel.Text = string.Empty;
        ErrorLabel.Visible = false;
    }
}
