using Content.Client.UserInterface.Systems.Actions.Controls;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Core.AudioDirector.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class FadeAudioTrackWindow : DefaultWindow
{
    public event Action<float, bool>? OnFadeConfirmed;

    private readonly bool _fadeIn;

    public FadeAudioTrackWindow(bool paused)
    {
        RobustXamlLoader.Load(this);

        _fadeIn = paused;

        ActionButton.Text = paused
            ? "Fade In"
            : "Fade Out";

        CancelButton.OnPressed += _ =>
            Close();

        ActionButton.OnPressed += _ =>
        {
            if (!float.TryParse(
                    DurationEdit.Text,
                    out var duration))
            {
                return;
            }

            OnFadeConfirmed?.Invoke(
                duration,
                _fadeIn);

            Close();
        };
    }
}
