using Content.Shared._Core.AudioDirector.Eui;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Core.AudioDirector.UI.Controls;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class AudioGroupCard : BoxContainer
{
    private bool _expanded;

    public int GroupId { get; }

    public event Action<int, bool>? OnExpandedChanged;
    public event Action<int>? OnDeletePressed;
    public event Action<int>? OnEditPressed;
    public event Action<int>? OnAddTrackPressed;
    public event Action<int, int>? OnDeleteTrackPressed;
    public event Action<int, int, float, bool>? OnUpdateTrackPressed;
    public event Action<int, int, bool>? OnSetTrackPausedPressed;
    public event Action<int, int, float>? OnSetTrackTimePressed;
    public event Action<int, int, float, bool>? OnFadeTrackPressed;

    public AudioGroupCard(
        AudioGroupEuiData group,
        bool expanded)
    {
        RobustXamlLoader.Load(this);

        GroupId = group.Id;
        _expanded = expanded;

        GroupNameLabel.Text = group.Name;
        TargetTypeLabel.Text = group.TargetType.ToString();

        HeaderButton.OnPressed += _ =>
            ToggleExpanded();

        CollapseButton.OnPressed += _ =>
            ToggleExpanded();

        DeleteGroupButton.OnPressed += _ =>
            OnDeletePressed?.Invoke(GroupId);

        EditGroupButton.OnPressed += _ =>
            OnEditPressed?.Invoke(GroupId);

        AddTrackButton.OnPressed += _ =>
            OnAddTrackPressed?.Invoke(GroupId);

        BuildTracks(group.Tracks);
        UpdateExpandedState();
    }

    public void SetRemoveMode(bool enabled)
    {
        DeleteGroupButton.Visible = enabled;
    }

    private void BuildTracks(
        AudioTrackEuiData[] tracks)
    {
        ContentContainer.RemoveAllChildren();

        if (tracks.Length == 0)
        {
            ContentContainer.AddChild(new Label
            {
                Text = "No tracks"
            });

            return;
        }

        foreach (var track in tracks)
        {
            var trackControl = new AudioTrackControl(
                GroupId,
                track);

            trackControl.OnDeleteTrackPressed += (groupId, trackId) =>
                OnDeleteTrackPressed?.Invoke(groupId, trackId);

            trackControl.OnUpdateTrackPressed += (groupId, trackId, volume, loop) =>
                OnUpdateTrackPressed?.Invoke(groupId, trackId, volume, loop);

            trackControl.OnSetTrackPausedPressed += (groupId, trackId, paused) =>
                OnSetTrackPausedPressed?.Invoke(groupId, trackId, paused);

            trackControl.OnSetTrackTimePressed += (groupId, trackId, time) =>
                OnSetTrackTimePressed?.Invoke(groupId, trackId, time);

            trackControl.OnFadeTrackPressed += (groupId, trackId, duration, fadeIn) =>
                OnFadeTrackPressed?.Invoke(groupId, trackId, duration, fadeIn);

            ContentContainer.AddChild(trackControl);
        }
    }

    private void ToggleExpanded()
    {
        _expanded = !_expanded;
        UpdateExpandedState();

        OnExpandedChanged?.Invoke(
            GroupId,
            _expanded);
    }

    private void UpdateExpandedState()
    {
        ContentContainer.Visible = _expanded;
        CollapseButton.Text = _expanded ? "▼" : "▶";
    }
}
